// @generated by tpt-telemetry-compiler. Do not edit.
use tpt_telemetry_compiler::{CompiledSchema, CompiledFormat, Seg, TypeName, CoercionTarget, RedactMode};

/// Build the compiled schema from generated segment data.
pub fn compiled_schema() -> CompiledSchema {
    let formats: Vec<CompiledFormat> = vec![
        CompiledFormat::new(
            "CiscoASA".to_string(),
            vec![
                Seg::Literal("%ASA-".to_string()),
                Seg::Capture { field: "severity".to_string(), ty: TypeName::Int },
                Seg::Literal("-".to_string()),
                Seg::Capture { field: "msg_id".to_string(), ty: TypeName::Int },
                Seg::Literal(": ".to_string()),
                Seg::Capture { field: "message".to_string(), ty: TypeName::String },
            ],
            vec![
                ("severity".to_string(), CoercionTarget::Enum(vec![
                    "EMERGENCY".to_string(),
                    "ALERT".to_string(),
                    "CRITICAL".to_string(),
                    "ERROR".to_string(),
                    "WARNING".to_string(),
                    "NOTICE".to_string(),
                    "INFO".to_string(),
                    "DEBUG".to_string(),
                ])),
            ],
            vec![
                ("message".to_string(), RedactMode::Mask),
            ],
        ),
    ];
    CompiledSchema::new(formats)
}
