//! Rust source code generation from a `.tpt-log` [`Schema`].
//!
//! `generate_rust` emits a self-contained Rust module that reconstructs a
//! [`CompiledSchema`] using the public builder API. The output is deterministic
//! and suitable for golden-file diffing (see `tests/golden/`), and — because it
//! only references the compiler's public types — it compiles and runs as a real
//! generated parser.

use crate::error::Result;
use tpt_telemetry_schema::ast::{CoercionTarget, PatternPart, RedactMode, Schema, TypeName};

/// Generate a Rust module that rebuilds the compiled schema from the public API.
pub fn generate_rust(schema: &Schema) -> Result<String> {
    let mut out = String::new();
    out.push_str("// @generated by tpt-telemetry-compiler. Do not edit.\n");
    out.push_str(
        "use tpt_telemetry_compiler::{CompiledSchema, CompiledFormat, Seg, TypeName, \
         CoercionTarget, RedactMode};\n\n",
    );

    out.push_str("/// Build the compiled schema from generated segment data.\n");
    out.push_str("pub fn compiled_schema() -> CompiledSchema {\n");
    out.push_str("    let formats: Vec<CompiledFormat> = vec![\n");

    for f in &schema.formats {
        out.push_str("        CompiledFormat::new(\n");
        out.push_str(&format!("            {:?}.to_string(),\n", f.name));

        // Segments.
        out.push_str("            vec![\n");
        for part in &f.pattern.parts {
            match part {
                PatternPart::Literal(s) => {
                    out.push_str(&format!("                Seg::Literal({:?}.to_string()),\n", s));
                }
                PatternPart::Capture(c) => {
                    let (field, ty) = if c.grok {
                        let field = c.field.clone().unwrap_or_else(|| c.name.clone());
                        let ty = if c.ty != TypeName::String {
                            c.ty
                        } else {
                            native_for_grok(&c.name)
                                .ok_or_else(|| {
                                    crate::error::CompileError::UnsupportedGrok(c.name.clone())
                                })?
                        };
                        (field, ty)
                    } else {
                        (c.name.clone(), c.ty)
                    };
                    out.push_str(&format!(
                        "                Seg::Capture {{ field: {:?}.to_string(), ty: TypeName::{} }},\n",
                        field, type_variant(ty)
                    ));
                }
            }
        }
        out.push_str("            ],\n");

        // Coercions.
        out.push_str("            vec![\n");
        for co in &f.coercions {
            match &co.target {
                CoercionTarget::Type(t) => {
                    out.push_str(&format!(
                        "                ({:?}.to_string(), CoercionTarget::Type(TypeName::{})),\n",
                        co.field,
                        type_variant(*t)
                    ));
                }
                CoercionTarget::Enum(variants) => {
                    out.push_str(&format!("                ({:?}.to_string(), CoercionTarget::Enum(vec![\n", co.field));
                    for v in variants {
                        out.push_str(&format!("                    {:?}.to_string(),\n", v));
                    }
                    out.push_str("                ])),\n");
                }
            }
        }
        out.push_str("            ],\n");

        // Redactions.
        out.push_str("            vec![\n");
        for r in &f.redactions {
            let mode = match r.mode {
                RedactMode::Hash => "Hash",
                RedactMode::Mask => "Mask",
            };
            out.push_str(&format!(
                "                ({:?}.to_string(), RedactMode::{}),\n",
                r.field, mode
            ));
        }
        out.push_str("            ],\n");

        out.push_str("        ),\n");
    }

    out.push_str("    ];\n");
    out.push_str("    CompiledSchema::new(formats)\n");
    out.push_str("}\n");
    Ok(out)
}

fn type_variant(t: TypeName) -> &'static str {
    match t {
        TypeName::Int => "Int",
        TypeName::Uint => "Uint",
        TypeName::Float => "Float",
        TypeName::Bool => "Bool",
        TypeName::String => "String",
        TypeName::Ipv4 => "Ipv4",
        TypeName::Ipv6 => "Ipv6",
        TypeName::Ip => "Ip",
        TypeName::Mac => "Mac",
        TypeName::Timestamp => "Timestamp",
    }
}

fn native_for_grok(name: &str) -> Option<TypeName> {
    use crate::compile::grok_native_type;
    grok_native_type(name)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tpt_telemetry_schema::parse;

    #[test]
    fn generates_deterministic_source() {
        let schema = parse(
            r#"format CiscoASA { pattern: "%ASA-%{severity:int}-%{msg_id:int}: %{message:string}"; coerce severity to enum { INFO, WARN }; }"#,
        )
        .unwrap();
        let a = generate_rust(&schema).unwrap();
        let b = generate_rust(&schema).unwrap();
        assert_eq!(a, b);
        assert!(a.contains("CompiledSchema::new"));
        assert!(a.contains("Seg::Capture"));
        assert!(a.contains("CoercionTarget::Enum"));
    }

    #[test]
    fn golden_file_matches_generated() {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests")
            .join("golden")
            .join("cisco_asa.rs");
        let golden = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("read golden file {:?}: {e}", path));
        let schema = parse(include_str!("../../examples/schemas/cisco_asa.tpt-log")).unwrap();
        let generated = generate_rust(&schema).unwrap();
        assert_eq!(generated, golden, "codegen drifted from golden file");
    }
}

